env: 'local'
postgres:
  host: 'localhost'
  port: 5432
  user: 'postgres'
  dbname: 'postgres'
  password: 'mysecretpassword'
rabbitmq:
  host: 'localhost'
  port: 5672
  user: 'guest'
  password: 'guest'